/**
 * Slugs for in-page section links.
 *
 * The menu entries in src/config/nav.ts and the `id` attributes on the cards
 * are both generated by this one function, from the same titles the cards
 * render. That is the point: a renamed service updates its own menu entry and
 * its own anchor together, so the menu can never end up pointing at an id that
 * no longer exists.
 */
export function slugify(text: string): string {
  return text
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/&/g, ' and ')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}
